services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-user
      TZ: Europe/London
    ports:
      - "${DB_PORT:-5435}:5432"
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: ms-user
    ports:
      - "${PORT:-8181}:8181"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge